#!/usr/bin/php
<?php
  require_once 'core/connection.php';
  require_once 'core/consoleFunctions.php';
  require_once 'vendor/autoload.php';

  echo shell_exec('clear');

  switch ($argc)
  {
    case '1':
      mostrarMenu();      
      break;

    case '2':
      switch ($argv[1])
      {
        case 'create:entity':

          $info_entity = createEntityTable();

          if($info_entity)
          {
            echo " -> Ahora vamos a crear el archivo de entidad.\n\n";
            echo " -> Presione una tecla para continuar...";
            fgets(STDIN);
            createEntity($info_entity['nombre'], $info_entity['campos']);
            echo "\n -> Entidad creada correctamente.\n\n";
          }

        break;

        case 'create:config':
          createConfig();
        break;

        case 'create:database':
          createDatabase();
        break;

        case 'check:config':
          checkConfig();
        break;

        default:
          mostrarMenu();
        break;
      }
  }


?>
